spring:
  datasource:
    dynamic:
      primary: master_user
      strict: false
      datasource:
        master_user:
          username: root
          password: root1234
          url: jdbc:mysql://127.0.0.1/student_course_select?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: dx-smart-teaching-assiatant-secret
  expiration: 86400000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /api-docs